# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Michele Bianchi"
# subtitle: "80% Games, 20% Other Stuff"
name: "Michele \"Jazzinghen\" Bianchi"
email: michele.bianchi@protonmail.com
description: >-
  Michele Bianchi is a software engineer with a soft spot for videogames, tabletop
  Role Playing Games, Anime, and writing code to make the life of his colleagues easier.
twitter:
  username: "jazzinghen"
github:
  username: "jazzinghen"

minimal_mistakes_skin: dark
search: true
search_provider: algolia

algolia:
  application_id: RGOG1GZ294
  index_name: DayStriders
  search_only_api_key: c579797944fb5f353e467fdc9d67d8ab
  powered_by: true

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: Asia/Tokyo
repository: "jazzinghen/DayStriders"
url: "https://jazzinghen.dev"
title_separator: "|"
copyright: "[![alt text](https://i.creativecommons.org/l/by-sa/4.0/80x15.png \"Creative Commons Licence\")](http://creativecommons.org/licenses/by-sa/4.0/) The contents of this website are licensed under [CC-BY-SA 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/)<br/>Site built with [Jekyll](https://jekyllrb.com/) and the [Basically Basic Theme](https://mmistakes.github.io/jekyll-theme-basically-basic/)"


include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-archives

social:
  links:
    - "https://twitter.com/Jazzinghen"
    - "https://github.com/jazzinghen"
    - "https://www.linkedin.com/in/jazzinghen/"


author:
  name   : "Michele \"Jazzinghen\" Bianchi"
  avatar : "/assets/images/self_portrait_square.png"
  bio: >-
    C++ Software Engineer with 5 years of multiplatform simulation, SDK and embedded
    systems development in R&D environments. 2 years of academic research experience
  location: "Tokyo, Japan"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jazzinghen"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jazzinghen/"
    - label: "LeetCode"
      icon: "fas fa-fw fa-keyboard"
      url: "https://leetcode.com/jazzinghen/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jazzinghen"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jazzinghen/"
    - label: "LeetCode"
      icon: "fas fa-fw fa-keyboard"
      url: "https://leetcode.com/jazzinghen/"
    - label: "Steam"
      icon: "fab fa-fw fa-steam"
      url: "https://steamcommunity.com/id/Jazzinghen"
    - label: "Spotify"
      icon: "fab fa-fw fa-spotify"
      url: "https://open.spotify.com/user/jqfsot0xfx3ynfdcebmouip5z"

defaults:
  # _posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
    values:
      layout: page
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
